name: Accessibility Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Start local server
        run: npx serve -p 3000 &
      
      # Give the server a moment to start up
      - name: Wait for server
        run: sleep 5
        
      - name: Run accessibility tests
        run: node run-axe-tests.js
        
      - name: Generate HTML report
        run: node generate-report.js
        
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: axe-results
          path: |
            accessibility-issues-results.json
            accessibility-fixed-results.json
            accessibility-report.html
            
      # Check if there are violations in the fixed demo (should be none)
      - name: Check for accessibility violations in fixed demo
        run: |
          VIOLATIONS=$(node -e "const result = require('./accessibility-fixed-results.json'); console.log(result.violations.length)")
          echo "Found $VIOLATIONS violations in the fixed demo"
          if [ "$VIOLATIONS" -gt 0 ]; then
            echo "::error::The supposedly fixed HTML file still has $VIOLATIONS accessibility violations!"
            exit 1
          else
            echo "✅ Fixed demo passes accessibility tests as expected"
          fi
